version: "3.8"
services:
    mongo:
        build: ./mongoDockerfile
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_NOT_ROOT_PASSWORD=${MONGO_NOT_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db
            - ./seed-data:/docker-entrypoint-initdb.d
        networks:
            - app-network

    server:
        build:
            context: ./server
        ports:
            - "8080:8080"
        environment:
            - DB_URL=${DB_URL}
            - NODE_ENV=production
        depends_on:
            - mongo
        networks:
            - app-network

    client:
        build:
            context: ./client
        ports:
            - "3000:3000"

        depends_on:
            - server
        networks:
            - app-network

volumes:
    mongo-data:

networks:
    app-network:
        driver: bridge
